version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hosting"
s3_prefix = "sam-hosting"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
