# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AmazonChimeSDKMessagingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmazonChimeSDKMessagingDemo
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'

  pod 'AWSChimeSDKMessaging'
  pod 'AWSChimeSDKIdentity'
  
  pod 'Starscream', '~> 4.0.0'

end
